#
# Copyright 2024 The Janus IDP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
openapi: '3.1.0'
info:
  version: '1.0'
  title: 'Bulk Import Backend'
  description: The Bulk Import Backend APIs allow users to bulk import Backstage entities into the backstage catalog from remote sources such as Git.
servers:
  - url: '{protocol}://{host}:{port}/{basePath}'
    variables:
      protocol:
        enum: [http, https]
        default: http
      host:
        default: localhost
      port:
        default: '7007'
      basePath:
        default: 'api/bulk-import-backend'
paths:
  /ping:
    get:
      operationId: ping
      summary: Check the health of the Bulk Import backend router
      tags: [Management]
      responses:
        200:
          description: The backend router for the Bulk Import backend is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    enum: ['ok']
              example:
                status: 'ok'

  /repositories:
    get:
      operationId: findAllRepositories
      summary: Fetch Organization Repositories accessible by Backstage Github Integrations
      security:
        - BearerAuth: []
      tags: [Repository]
      parameters:
        - in: query
          name: pagePerIntegration
          description: the page number for each Integration
          schema:
            type: integer
            default: 1
        - in: query
          name: sizePerIntegration
          description: the number of items per Integration to return per page
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: Repository list was fetched successfully with no errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryList'
              examples:
                multipleRepos:
                  $ref: '#/components/examples/multipleRepos'
        500:
          description: Generic error when there are errors and no repository is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryList'
              examples:
                repositoryListErrors:
                  $ref: '#/components/examples/repositoryListErrors'

  /imports:
    get:
      operationId: findAllImports
      summary: Fetch Import Jobs
      security:
        - BearerAuth: []
      tags: [Import]
      parameters:
        - in: query
          name: pagePerIntegration
          description: the page number for each Integration
          schema:
            type: integer
            default: 1
        - in: query
          name: sizePerIntegration
          description: the number of items per Integration to return per page
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: Import Jobs list was fetched successfully with no errors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Import'
              examples:
                twoImports:
                  $ref: '#/components/examples/twoImports'
        500:
          description: Generic error

    post:
      operationId: createImportJobs
      summary: Submit Import Jobs
      security:
        - BearerAuth: []
      tags: [Import]
      parameters:
        - in: query
          name: dryRun
          description: whether to perform a dry-run to check if entity name collisions would occur in the catalog
          schema:
            type: boolean
            default: 'false'
      requestBody:
        description: List of Import jobs to create
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ImportRequest'
            examples:
              multipleImportRequests:
                $ref: '#/components/examples/multipleImportRequests'
      responses:
        202:
          description:
            Import Jobs request was submitted successfully to the API.
            Check the status in each item of the response body list to see their individual status.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Import'
              examples:
                twoImports:
                  $ref: '#/components/examples/twoImports'

  /import/by-repo:
    get:
      operationId: findImportStatusByRepo
      summary: Get Import Status by repository
      security:
        - BearerAuth: []
      tags: [Import]
      parameters:
        - in: query
          name: repo
          description: the full URL to the repo
          schema:
            type: string
        - in: query
          name: defaultBranch
          description: the name of the default branch
          schema:
            type: string
            default: 'main'
      responses:
        200:
          description: Import Job status was determined successfully with no errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Import'
              examples:
                singleImportStatusForRepo:
                  $ref: '#/components/examples/singleImportStatusForRepo'
        500:
          description: Generic error

    delete:
      operationId: deleteImportByRepo
      summary: Delete Import by repository
      security:
        - BearerAuth: []
      tags: [Import]
      parameters:
        - in: query
          name: repo
          description: the full URL to the repo
          schema:
            type: string
        - in: query
          name: defaultBranch
          description: the name of the default branch
          schema:
            type: string
            default: 'main'
      responses:
        204:
          description: Import Job was successfully delete with no errors
        500:
          description: Generic error

components:
  schemas:
    RepositoryList:
      title: Repository List
      type: object
      properties:
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/Repository'
        errors:
          type: array
          items:
            type: string
        totalCount:
          type: integer
        pagePerIntegration:
          type: integer
        sizePerIntegration:
          type: integer

    Repository:
      title: Repository
      type: object
      properties:
        id:
          type: string
          description: unique identifier
        name:
          type: string
          description: repository name
        url:
          type: string
          description: repository URL
        organization:
          type: string
          description: organization which the repository is part of
        importStatus:
          $ref: '#/components/schemas/ImportStatus'
        defaultBranch:
          type: string
          description: default branch
        errors:
          type: array
          items:
            type: string

    ApprovalTool:
      type: string
      enum:
        - GIT
        - SERVICENOW

    ImportStatus:
      type: string
      nullable: true
      description: Import Job status
      enum:
        #- WAIT_APPROVAL
        - ADDED
        #- WAIT_PR_START
        - WAIT_PR_APPROVAL
        #- PR_REJECTED
        #- WAIT_SERVICENOW_START
        #- WAIT_SERVICENOW_RESOLUTION
        - PR_ERROR
        #- SERVICENOW_ERROR
        #- SERVICENOW_TICKET_REJECTED
        - null

    Import:
      title: Import Job
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/ImportStatus'
        catalogEntityName:
          type: string
          description: Specified entity name in the catalog. Filled only in response for dry-run import requests.
        errors:
          type: array
          items:
            type: string
        approvalTool:
          $ref: '#/components/schemas/ApprovalTool'
        repository:
          type: object
          properties:
            name:
              type: string
              description: repository name
            url:
              type: string
              description: repository URL
            organization:
              type: string
              description: organization which the repository is part of
        github:
          type: object
          description: GitHub details. Applicable if approvalTool is git.
          properties:
            pullRequest:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the Pull Request
                number:
                  type: number
                  description: Pull Request number

    ImportRequest:
      title: Import Job request
      type: object
      required:
        - repository
      properties:
        approvalTool:
          $ref: '#/components/schemas/ApprovalTool'
        catalogEntityName:
          type: string
          description: Expected Entity name in the catalog. Relevant only if the 'dryRun' query parameter is set to 'true'.
        repository:
          type: object
          required:
            - url
          properties:
            name:
              type: string
              description: repository name
            url:
              type: string
              description: repository URL
            organization:
              type: string
              description: organization which the repository is part of
            defaultBranch:
              type: string
              description: default branch
        catalogInfoContent:
          type: string
          description: content of the catalog-info.yaml to include in the import Pull Request.
        github:
          type: object
          description: GitHub details. Applicable if approvalTool is git.
          properties:
            pullRequest:
              type: object
              description: Pull Request details. Applicable if approvalTool is git.
              properties:
                title:
                  type: string
                  description: title of the Pull Request
                body:
                  type: string
                  description: body of the Pull Request

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Backstage Permissions Framework JWT

  examples:
    multipleRepos:
      summary: Multiple repositories
      value:
        errors: []
        repositories:
          - id: 'unique-id-1'
            name: 'pet-app'
            url: 'https://github.com/my-org/pet-app'
            organization: 'my-org'
            importStatus: 'WAIT_PR_APPROVAL'
            defaultBranch: 'main'
          - id: 'unique-id-2'
            name: 'project-zero'
            url: 'https://ghe.example.com/my-other-org/project-zero'
            organization: 'my-other-org'
            importStatus: 'PR_REJECTED'
            defaultBranch: 'dev'
          - id: 'unique-id-2'
            name: 'project-one'
            defaultBranch: 'trunk'
            url: 'https://ghe.example.com/my-other-org-2/project-one'
            organization: 'my-other-org-2'

    repositoryListErrors:
      summary: Errors when listing repositories
      value:
        errors:
          - 'Github App with ID 2 failed spectacularly'
        repositories: []

    twoImports:
      summary: Two import job requests
      value:
        - id: 'bulk-import-id-1'
          status: 'WAIT_PR_APPROVAL'
          errors: []
          approvalTool: GIT
          repository:
            name: 'pet-app'
            url: 'https://github.com/my-org/pet-app'
            organization: 'my-org'
          github:
            pullRequest:
              url: 'https://github.com/my-org/pet-app/pull/1'
              number: 1
        - id: 'bulk-import-id-2'
          status: 'PR_REJECTED'
          errors: []
          approvalTool: GIT
          repository:
            name: 'pet-app-test'
            url: 'https://github.com/my-org/pet-app-test'
            organization: 'my-org'
          github:
            pullRequest:
              url: 'https://github.com/my-org/pet-app-test/pull/10'
              number: 10

    singleImportStatusForRepo:
      summary: Single import job status for given repo
      value:
        id: 'bulk-import-id-1'
        status: 'WAIT_PR_APPROVAL'
        errors: []
        approvalTool: GIT
        repository:
          name: 'pet-app'
          url: 'https://github.com/my-org/pet-app'
          organization: 'my-org'
        github:
          pullRequest:
            url: 'https://github.com/my-org/pet-app/pull/1'
            number: 1

    multipleImportRequests:
      summary: Multiple import requests
      value:
        - approvalTool: GIT
          repository:
            name: 'pet-app'
            url: 'https://github.com/my-org/pet-app'
            organization: 'my-org'
            defaultBranch: main
          github:
            pullRequest:
              title: 'Add default catalog-info.yaml to import to Red Hat Developer Hub'
        - approvalTool: GIT
          repository:
            name: 'project-zero'
            url: 'https://ghe.example.com/my-other-org/project-zero'
            organization: 'my-other-org'
            defaultBranch: dev
          github:
            pullRequest:
              title: 'Add custom catalog-info.yaml to import to Red Hat Developer Hub'
              body: |-
                This pull request adds a **Backstage entity metadata file** to this repository so that the component can be added to the Red Hat Developer Hub software catalog.

                After this pull request is merged, the component will become available.

                For more information, read an [overview of the Backstage software catalog](https://backstage.io/docs/features/software-catalog/).
          catalogInfoContent: |-
            apiVersion: backstage.io/v1alpha1
            kind: Component
            metadata:
              name: project-zero
              annotations:
                github.com/project-slug: my-other-org/project-zero
                acme.com/custom-annotation: my-value
            spec:
              type: other
              lifecycle: unknown
              owner: my-other-org
